version: '3.9'

services:
  backend:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: unless-stopped
    depends_on: 
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
     - POSTGRES_USER=test
     - POSTGRES_PASSWORD=test1234
     - POSTGRES_DB=gogive_test
    ports:
     - 5432:5432
    volumes: 
     - pgdata:/var/lib/postgresql/data:rw
    restart: unless-stopped

volumes:
 pgdata:
