version: '3.9'

services:
  backend:
    container_name: gogive-backend
    build:
      context: . 
      dockerfile: Dockerfile
      args:
        GO_PORT: ${go_port:-4000} 
        GO_ENV: "development" 
        GO_DB_MAX_OPEN_CONNS: ${GO_DB_MAX_OPEN_CONNS:-25}
        GO_DB_MAX_IDLE_CONNS: ${GO_DB_MAX_IDLE_CONNS:-25}
        GO_DB_MAX_IDLE_TIME: ${GO_DB_MAX_IDLE_TIME:-15m}
        GO_RATE_LIMITER_RPS: ${GO_RATE_LIMITER_RPS:-2}
        GO_RATE_LIMITER_BURST: ${GO_RATE_LIMITER_BURST:-4}
        GO_RATE_LIMITER_ENABLED: ${GO_RATE_LIMITER_ENABLED:-false}
    ports:
      - ${go_port:-4000}:${go_port:-4000}
    environment:
      GOGIVE_DB_DSN: "postgres://gogive_test:test1234@postgres/gogive_test?sslmode=disable"
    restart: unless-stopped
    depends_on: 
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
     - POSTGRES_USER=test
     - POSTGRES_PASSWORD=test1234
     - POSTGRES_DB=gogive_test
    ports:
     - 5432:5432
    volumes: 
     - pgdata:/var/lib/postgresql/data:rw
    restart: unless-stopped
  demo-pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com 
      PGADMIN_DEFAULT_PASSWORD: test1234 
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
    - "8889:80"
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin 
    depends_on:
      - postgres
  mailcatcher: # https://mailcatcher.me
    container_name: mailcatcher
    image: jeanberu/mailcatcher
    ports:
      - "1025:1025" # SMTP server
      - "1080:1080" # UI
    restart: unless-stopped
volumes:
 pgdata:
 pgadmin:
