drop index IF EXISTS BAN_FK;

drop index IF EXISTS BANS_PK;

drop index IF EXISTS CATEGORIES_PK;

drop index IF EXISTS HAVE_PERMISSION2_FK;

drop index IF EXISTS HAVE_PERMISSION_FK;

drop index IF EXISTS CONTAINS_FK;

drop index IF EXISTS EXIST_IN_FK;

drop index IF EXISTS CREATE_FK;

drop index IF EXISTS ITEMS_PK;

drop index IF EXISTS LOCATIONS_PK;

drop index IF EXISTS PERMISSIONS_PK;

drop index IF EXISTS ROLES_PK;

drop index IF EXISTS HAVE_TOKEN_FK;

drop index IF EXISTS TOKENS_PK;

drop index IF EXISTS HAVE_ROLE_FK;

drop index IF EXISTS LIVES_IN_FK;

drop index IF EXISTS USERS_PK;
